### ISSUE TITLE
If subsections are missing the library raises an error

### ISSUE THREAD

**Issue by azazel75** [stephen-bunn/file-config#24]
### Expected Behavior
When a subsection of a configuration is missing from a serialized representation I would expect the deserialization to conclude without errors as it's the role of validation to check the fitting of a configuration instance. 
For example, given the following configuration definition:
```python
    @file_config.config
    class TestConfig:

        @file_config.config
        class InnerConfig:
            foo = file_config.var(str, default="Default", required=False)

        inner = file_config.var(InnerConfig, required=False)
        bar = file_config.var(str, default="Default", required=False)
```
and the following YAML file
```yaml
bar: goofy
```
I expect the `load()` operation to complete without errors and to return an instance with `bar == "goofy"` and  `inner == None`

### Current Behavior
Raises a generic error trying to do `None.get()` 

### Possible Solution
Take care of the case when the subsection isn't present in the containing section dict

### Your Environment

* File Config Version: 0.3.5
* Python Version: 3.7
* Operating System and Version: NixOS GNU/Linux
* Link to your branch (if applicable):
---
❤️ Thank you!

**Comment by stephen-bunn** [comment]
Fixed in #25
